name: fp_ts
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.7.3
  - numpy=1.15.4
  - spacy=2.0.16
  - pandas=1.0.1
  - scikit-learn=0.20.1
  - matplotlib=3.2.1
  - pyspark=2.4.5
  - pyarrow==0.14.0
  - fbprophet=0.6